name: GitHub Action Demo
on: 
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    paths-ignore: [.github/**]        
  schedule:
    - cron: '15 6 * * 0'  
  workflow_dispatch:
    
jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job triggered by: ${{ github.event_name }}"
          echo "Triggered from branch: ${{ github.ref }}"
          
      - uses: actions/checkout@v3
      
      - name: List all files in repo
        run : |
          echo "file in repo ${{ github.repository }}:"
          tree
